### ISSUE TITLE
implement controller.run(stop_criterion=) method that takes lambda function that specifies stopping criterion

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora-workflow#18]

**Comment by hollandjg** [comment]
You can already do this, not within the "run" but from outside. 

For instance, to run a `controller` until it has 9 models:
```python
from itertools import takewhile
controller = Controller(...<your arguments here>)
takewhile(lambda c: len(c.data.models) < 9, controller)
```

... or in the functional approach, you need a `State` which keeps the history, so we define one first:
```python
@dataclass(frozen=True)
class AppendState(State):
    model: List[BaseEstimator] = field(default_factory=list, metadata={"delta": "append"})
    ...

s = AppendState(...)

while len(s.model) < 9:
    s = experimentalist(s, n_samples=10)
    s = experiment_runner(s)
    s = theorist(s)
```

It would be possible to implement this as part of the Controller `run` method, also using the `next()` approach.

**Comment by musslick** [comment]
> You can already do this, not within the "run" but from outside.
> 
> For instance, to run a `controller` until it has 9 models:
> 
> ```python
> from itertools import takewhile
> controller = Controller(...<your arguments here>)
> takewhile(lambda c: len(c.data.models) < 9, controller)
> ```
> 
> ... or in the functional approach, you need a `State` which keeps the history, so we define one first:
> 
> ```python
> @dataclass(frozen=True)
> class AppendState(State):
>     model: List[BaseEstimator] = field(default_factory=list, metadata={"delta": "append"})
>     ...
> 
> s = AppendState(...)
> 
> while len(s.model) < 9:
>     s = experimentalist(s, n_samples=10)
>     s = experiment_runner(s)
>     s = theorist(s)
> ```
> 
> It would be possible to implement this as part of the Controller `run` method, also using the `next()` approach.

Thanks for the example! That's exactly how I implemented it in the Tutorial. However, @chadcwilliams made the great suggestion to condense the `takewhile` into a single-liner, just by implementing a run function that can be passed a stopping criterion. This seems more intuitive than the `takewhile` solution and is more aligned with the simple Cycle usage via the `run()` function.

That said, the "AppendState" way of doing it seems way more attractive to me! :)

**Comment by hollandjg** [comment]
If anyone would like to take this on (and anyone could) but isn’t sure about how to do it, just reach out!

**Comment by hollandjg** [comment]
This is outdated
